org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.22
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=legendaryinventory
mod_name=Legendary Inventory
mod_license=All Rights Reserved
mod_version=1.1.0
mod_group_id=com.krampus.legendaryinventory
mod_authors=Krampus
mod_description=Replaces inventory 36 vanilla slots with an unlimited slot number governed by a weight system
